# Generated by Django 4.0.2 on 2022-02-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediumReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='sent date')),
                ('medium', models.CharField(max_length=255, verbose_name="medium's name")),
                ('receiver', models.CharField(max_length=255, verbose_name='receiver')),
            ],
            options={
                'verbose_name': 'medium report',
                'verbose_name_plural': 'medium reports',
            },
        ),
    ]
