
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    networks:
      - main
    ports:
      - "5672:5672"
    restart: always

  celery_worker:
    container_name: celery_worker
    command: "celery -A A worker -l INFO"
    depends_on:
      - app
      - rabbitmq
    build: .
    environment:
      - C_FORCE_ROOT="true"
    networks:
      - main
    restart: always

  app:
    build: .
    command: sh -c "python manage.py migrate && gunicorn A.wsgi -b 0.0.0.0:8000"
    container_name: app
    volumes:
      - .:/code/
    depends_on:
      - rabbitmq
    expose:
      - "8000"
    networks:
      - main
    restart: always

  nginx:
    container_name: nginx
    command: nginx -g 'daemon off;'
    depends_on:
      - app
    image: nginx:latest
    networks:
      - main
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf


networks:
  main:
