# Generated by Django 4.0.2 on 2022-02-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveBigIntegerField(verbose_name='order number')),
                ('amount', models.PositiveBigIntegerField(verbose_name='price')),
                ('track_id', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='unique payment ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='status paid')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='date paid')),
                ('ref_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='refrence payment number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
            },
        ),
    ]
